/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSinaisRouteImport } from './routes/_authenticated/sinais'
import { Route as AuthenticatedSalvosRouteImport } from './routes/_authenticated/salvos'
import { Route as AuthenticatedRevisarRouteImport } from './routes/_authenticated/revisar'
import { Route as AuthenticatedPostsViraisRouteImport } from './routes/_authenticated/posts-virais'
import { Route as AuthenticatedPlanejamentoRouteImport } from './routes/_authenticated/planejamento'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedIntegracoesRouteImport } from './routes/_authenticated/integracoes'
import { Route as AuthenticatedIcpRouteImport } from './routes/_authenticated/icp'
import { Route as AuthenticatedFunilRouteImport } from './routes/_authenticated/funil'
import { Route as AuthenticatedConteudoRouteImport } from './routes/_authenticated/conteudo'
import { Route as AuthenticatedCadenciasRouteImport } from './routes/_authenticated/cadencias'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSinaisRoute = AuthenticatedSinaisRouteImport.update({
  id: '/sinais',
  path: '/sinais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalvosRoute = AuthenticatedSalvosRouteImport.update({
  id: '/salvos',
  path: '/salvos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRevisarRoute = AuthenticatedRevisarRouteImport.update({
  id: '/revisar',
  path: '/revisar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostsViraisRoute =
  AuthenticatedPostsViraisRouteImport.update({
    id: '/posts-virais',
    path: '/posts-virais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanejamentoRoute =
  AuthenticatedPlanejamentoRouteImport.update({
    id: '/planejamento',
    path: '/planejamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegracoesRoute =
  AuthenticatedIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIcpRoute = AuthenticatedIcpRouteImport.update({
  id: '/icp',
  path: '/icp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFunilRoute = AuthenticatedFunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConteudoRoute = AuthenticatedConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCadenciasRoute = AuthenticatedCadenciasRouteImport.update({
  id: '/cadencias',
  path: '/cadencias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/cadencias': typeof AuthenticatedCadenciasRoute
  '/conteudo': typeof AuthenticatedConteudoRoute
  '/funil': typeof AuthenticatedFunilRoute
  '/icp': typeof AuthenticatedIcpRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/posts-virais': typeof AuthenticatedPostsViraisRoute
  '/revisar': typeof AuthenticatedRevisarRoute
  '/salvos': typeof AuthenticatedSalvosRoute
  '/sinais': typeof AuthenticatedSinaisRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/cadencias': typeof AuthenticatedCadenciasRoute
  '/conteudo': typeof AuthenticatedConteudoRoute
  '/funil': typeof AuthenticatedFunilRoute
  '/icp': typeof AuthenticatedIcpRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/posts-virais': typeof AuthenticatedPostsViraisRoute
  '/revisar': typeof AuthenticatedRevisarRoute
  '/salvos': typeof AuthenticatedSalvosRoute
  '/sinais': typeof AuthenticatedSinaisRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/cadencias': typeof AuthenticatedCadenciasRoute
  '/_authenticated/conteudo': typeof AuthenticatedConteudoRoute
  '/_authenticated/funil': typeof AuthenticatedFunilRoute
  '/_authenticated/icp': typeof AuthenticatedIcpRoute
  '/_authenticated/integracoes': typeof AuthenticatedIntegracoesRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/_authenticated/posts-virais': typeof AuthenticatedPostsViraisRoute
  '/_authenticated/revisar': typeof AuthenticatedRevisarRoute
  '/_authenticated/salvos': typeof AuthenticatedSalvosRoute
  '/_authenticated/sinais': typeof AuthenticatedSinaisRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cadencias'
    | '/conteudo'
    | '/funil'
    | '/icp'
    | '/integracoes'
    | '/leads'
    | '/planejamento'
    | '/posts-virais'
    | '/revisar'
    | '/salvos'
    | '/sinais'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/cadencias'
    | '/conteudo'
    | '/funil'
    | '/icp'
    | '/integracoes'
    | '/leads'
    | '/planejamento'
    | '/posts-virais'
    | '/revisar'
    | '/salvos'
    | '/sinais'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/cadencias'
    | '/_authenticated/conteudo'
    | '/_authenticated/funil'
    | '/_authenticated/icp'
    | '/_authenticated/integracoes'
    | '/_authenticated/leads'
    | '/_authenticated/planejamento'
    | '/_authenticated/posts-virais'
    | '/_authenticated/revisar'
    | '/_authenticated/salvos'
    | '/_authenticated/sinais'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sinais': {
      id: '/_authenticated/sinais'
      path: '/sinais'
      fullPath: '/sinais'
      preLoaderRoute: typeof AuthenticatedSinaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salvos': {
      id: '/_authenticated/salvos'
      path: '/salvos'
      fullPath: '/salvos'
      preLoaderRoute: typeof AuthenticatedSalvosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revisar': {
      id: '/_authenticated/revisar'
      path: '/revisar'
      fullPath: '/revisar'
      preLoaderRoute: typeof AuthenticatedRevisarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/posts-virais': {
      id: '/_authenticated/posts-virais'
      path: '/posts-virais'
      fullPath: '/posts-virais'
      preLoaderRoute: typeof AuthenticatedPostsViraisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planejamento': {
      id: '/_authenticated/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof AuthenticatedPlanejamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integracoes': {
      id: '/_authenticated/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AuthenticatedIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/icp': {
      id: '/_authenticated/icp'
      path: '/icp'
      fullPath: '/icp'
      preLoaderRoute: typeof AuthenticatedIcpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funil': {
      id: '/_authenticated/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof AuthenticatedFunilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conteudo': {
      id: '/_authenticated/conteudo'
      path: '/conteudo'
      fullPath: '/conteudo'
      preLoaderRoute: typeof AuthenticatedConteudoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadencias': {
      id: '/_authenticated/cadencias'
      path: '/cadencias'
      fullPath: '/cadencias'
      preLoaderRoute: typeof AuthenticatedCadenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCadenciasRoute: typeof AuthenticatedCadenciasRoute
  AuthenticatedConteudoRoute: typeof AuthenticatedConteudoRoute
  AuthenticatedFunilRoute: typeof AuthenticatedFunilRoute
  AuthenticatedIcpRoute: typeof AuthenticatedIcpRoute
  AuthenticatedIntegracoesRoute: typeof AuthenticatedIntegracoesRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedPlanejamentoRoute: typeof AuthenticatedPlanejamentoRoute
  AuthenticatedPostsViraisRoute: typeof AuthenticatedPostsViraisRoute
  AuthenticatedRevisarRoute: typeof AuthenticatedRevisarRoute
  AuthenticatedSalvosRoute: typeof AuthenticatedSalvosRoute
  AuthenticatedSinaisRoute: typeof AuthenticatedSinaisRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCadenciasRoute: AuthenticatedCadenciasRoute,
  AuthenticatedConteudoRoute: AuthenticatedConteudoRoute,
  AuthenticatedFunilRoute: AuthenticatedFunilRoute,
  AuthenticatedIcpRoute: AuthenticatedIcpRoute,
  AuthenticatedIntegracoesRoute: AuthenticatedIntegracoesRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedPlanejamentoRoute: AuthenticatedPlanejamentoRoute,
  AuthenticatedPostsViraisRoute: AuthenticatedPostsViraisRoute,
  AuthenticatedRevisarRoute: AuthenticatedRevisarRoute,
  AuthenticatedSalvosRoute: AuthenticatedSalvosRoute,
  AuthenticatedSinaisRoute: AuthenticatedSinaisRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
